---
disabled_rules: # rule identifiers to exclude from running
  - variable_name_min_length
  - line_length
  - force_cast
  - type_name
  - type_body_length
included: # paths to include during linting. `--path` is ignored if present.
  - Captured
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Vendor
