#!/bin/sh
# -*- sh -*- vim:set ft=sh ai et sw=4 sts=4:
codesign -f -v -s "3rd Party Mac Developer Application: Christopher Sexton" "build/App Store Release/Captured.app"
productbuild --component "build/App Store Release/Captured.app" "/Applications" --sign "3rd Party Mac Developer Application: Christopher Sexton" "captured.pkg"
